[program:example-node-app]
directory=/var/www/example-node-app

command=npm run dev -- --host 0.0.0.0 --port 3000

autostart=true
autorestart=true
startretries=3

stopasgroup=true
killasgroup=true

stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

environment=HOME="/var/www"